### ISSUE TITLE
master -> main

### ISSUE THREAD

**Issue by kaftand** [quantregpy/quantregpy#20]

**Comment by paulkaefer** [comment]
@kaftand I created the `main` branch, but it's not letting me delete `master`. Can you do so here: https://github.com/quantregpy/quantregpy/branches?

**Comment by paulkaefer** [comment]
@kaftand one more note: I followed [this guide](https://www.techrepublic.com/article/github-to-replace-master-with-main-starting-in-october-what-developers-need-to-know/). You won't need to do anything; I just wanted to add for tracking purposes.

You might want to run `git config --global init.defaultBranch main` (not in the above guide). Also if any of the actions fail, it might be if they are pointed at the `master` branch, though it may be automatic.

**Comment by kaftand** [comment]
looks good, thanks paul!
